export const tourPackages = [
  {
    id: 1,
    image: "images/beach.jpg",
    title: "Beach Bliss",
    duration: "5 Nights | 6 Days",
    rating: 4.7,
    flights: 2,
    hotels: 1,
    transfers: 3,
    activities: 6,
    price: "₹88,952",
  },
  {
    id: 2,
    image: "images/mount.jpg",
    title: "Himalayan Escape",
    duration: "7 Nights | 8 Days",
    rating: 4.1,
    flights: 1,
    hotels: 2,
    transfers: 4,
    activities: 2,
    price: "₹40,000",
  },
  {
    id: 3,
    image: "images/temple.jpg",
    title: "Heritage Tour",
    duration: "4 Nights | 5 Days",
    rating: 4.2,
    flights: 2,
    hotels: 1,
    transfers: 1,
    activities: 4,
    price: "₹35,000",
  },
  {
    id: 4,
    image: "images/lakeview.jpg",
    title: "Kerala Backwaters",
    duration: "3 Nights | 4 Days",
    rating: 4.5,
    flights: 2,
    hotels: 2,
    transfers: 1,
    activities: 3,
    price: "₹65,500",
  },
  {
    id: 5,
    image: "images/templefront.jpg",
    title: "Desert Safari",
    duration: "2 Nights | 3 Days",
    rating: 4.0,
    flights: 1,
    hotels: 1,
    transfers: 2,
    activities: 2,
    price: "₹25,000",
  },
];